#define CMD_ALL_SET 1
#define CMD_ALL_RESET 2
#define CMD_POWER_ON 3
#define CMD_POWER_OFF 4
#define CMD_DOT_SET 5
#define CMD_DOT_RESET 6
#define CMD_DURATION_SET 7
#define CMD_TIME_GET 8
#define CMD_SLEEP 9
#define CMD_TEST 10
#define CMD_CALIBRATE 11
