### Turn backlight on
GET http://192.168.178.61/lighton

### Turn backlight off
GET http://192.168.178.61/lightoff

### Turn display on
GET http://192.168.178.61/displayon


### Turn display off
GET http://192.168.178.61/displayoff

### Get current picture
GET http://192.168.178.61/status

### Get current picture
GET http://192.168.178.61/data


### set picture (base64 encoded)
POST http://192.168.178.61/data
content-type: application/json

{
  "frameBuffer": "AAAAAAAA///8AAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgCAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAEAAAAAAAAAAAAAAAAAAAAgAAUAAAAAAAAAAAAAAAAAAAA///8AAAAAAAAAAAA"
}

### set picture block (base64 encoded)
POST http://192.168.178.61/datablock
content-type: application/json

{
  "left": 16,
  "top": 5,
  "width": 24,
  "height": 10,
  "frameBuffer": "VVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqq"
}

### small text
POST http://192.168.178.61/textSmall
content-type: application/json

{
  line1: " Weeks of coding can save",
  line2: "  you hours of planning"
}

### small text with regional characters
POST http://192.168.178.61/textSmall
content-type: application/json

{
  line1: "Käsesoßenrührlöffel",
  line2: "ЗДРАВСТВУЙ МИР!"
}

### small text
POST http://192.168.178.61/textSmall
content-type: application/json

{
  line1: "I HAVE A FEELING WE'RE",
  line2: "NOT IN KANSAS ANYMORE"
}

### small text
POST http://192.168.178.61/textSmall
content-type: application/json

{
  line1: "I'm sorry Dave,",
  line2: "I'm afraid I can't do that"
}

### big text
POST http://192.168.178.61/textBig
content-type: application/json

{
  text: "       Hello World!"
}

### big text
POST http://192.168.178.61/textBig
content-type: application/json

{
  text: " Gute Besserung!"
}

### bus with route number
POST http://192.168.178.61/bus
content-type: application/json

{
  route: 130,
  line1: "S P A N D A U",
  line2: "Nervenklinik"
}

### bus with glyph
POST http://192.168.178.61/bus
content-type: application/json

{
  glyph: "tram",
  line1: "ich verstehe immer",
  line2: "nur Bahnhof"
}


### long text
POST http://192.168.178.61/textBig
content-type: application/json

{
  text: "012345678901234"
}

### POST game of life
POST http://192.168.178.61/gameoflife
content-type: application/json

{
}

### POST run pacman
POST http://192.168.178.61/pacman
content-type: application/json

{
}

### POST start counter
POST http://192.168.178.61/counter
content-type: application/json

{
}


### clear screen
POST http://192.168.178.61/cls
content-type: application/json

{
}

###  set all pixels
POST http://192.168.178.61/test
content-type: application/json

{
}

###  Let it snow
POST http://192.168.178.61/newyear
content-type: application/json

{
}